/*
 * SCATERNET — regenerate src/images-manifest.js and src/audio-manifest.js from
 * whatever is actually on disk under assets/. Run after assets land.
 *   node tools/build_manifests.mjs
 */
import { readdirSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const IMG_EXT = /\.(png|jpe?g|webp|gif)$/i;
const AUD_EXT = /\.(mp3|ogg|wav|m4a|webm)$/i;

function list(dir, re) {
  const p = join(root, dir);
  if (!existsSync(p)) return [];
  return readdirSync(p).filter((f) => re.test(f)).sort();
}

const images = list("assets/images", IMG_EXT);
writeFileSync(
  join(root, "src/images-manifest.js"),
  `/* SCATERNET — bundled image filenames (assets/images/*). Auto-generated by tools/build_manifests.mjs. */\n` +
    `globalThis.ScaternetImagesList = ${JSON.stringify(images, null, 2)};\n`
);

const audio = {
  music: list("assets/audio/music", AUD_EXT),
  video: list("assets/audio/video", AUD_EXT),
  scats: list("assets/audio/scats", AUD_EXT),
  farts: list("assets/audio/farts", AUD_EXT),
};
writeFileSync(
  join(root, "src/audio-manifest.js"),
  `/* SCATERNET — bundled audio filenames. Auto-generated by tools/build_manifests.mjs. */\n` +
    `globalThis.ScaternetAudioAssets = ${JSON.stringify(audio, null, 2)};\n`
);

console.log(
  `images: ${images.length} | music: ${audio.music.length} video: ${audio.video.length} scats: ${audio.scats.length} farts: ${audio.farts.length}`
);
