#!/usr/bin/env python3
"""Fetch REAL dog photos for the bundled fallback pack — openly licensed only.

Sources them via the Openverse API filtered to CC0 + Public Domain Mark, so no
attribution is legally required and they are safe to redistribute inside a
published extension. Each photo is centre-cropped to a square and resized, and
full provenance is recorded in assets/dogs/SOURCES.md.

Outputs: assets/dogs/dog-01.jpg ... dog-NN.jpg, src/dogs-manifest.js, SOURCES.md
Run:  ./.venv/bin/python tools/fetch_real_dogs.py
"""
import io
import json
import subprocess
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
DOGS = ROOT / "assets" / "dogs"
MANIFEST = ROOT / "src" / "dogs-manifest.js"
SOURCES = DOGS / "SOURCES.md"

N = 16
OUT_SIZE = 512
UA = "chienternet/1.0 (personal joke extension; dog photos, CC0/PDM only)"
# Anonymous Openverse is capped at page_size=20, so we page through results.
# CC0 only: the Public-Domain-Mark bucket surfaces antique museum scans, not dogs.
API = ("https://api.openverse.org/v1/images/"
       "?q=dog&license=cc0&extension=jpg&size=medium&mature=false&page_size=20&page={page}")


def get(url, timeout=25):
    # curl proved reliable where urllib hit anon-rate 401s.
    p = subprocess.run(
        ["curl", "-sS", "-L", "-A", UA, "--max-time", str(timeout), url],
        capture_output=True,
    )
    if p.returncode != 0:
        raise RuntimeError(f"curl failed ({p.returncode}): {p.stderr.decode()[:120]}")
    return p.stdout


def square(img: Image.Image, size: int) -> Image.Image:
    img = img.convert("RGB")
    w, h = img.size
    s = min(w, h)
    left, top = (w - s) // 2, (h - s) // 2
    return img.crop((left, top, left + s, top + s)).resize((size, size), Image.LANCZOS)


def main():
    DOGS.mkdir(parents=True, exist_ok=True)
    # Clear any previous pack (cartoons or old fetch).
    for old in DOGS.glob("dog-*.png"):
        old.unlink()
    for old in DOGS.glob("dog-*.jpg"):
        old.unlink()

    print("Querying Openverse for CC0/PDM dog photos …")
    files, sources = [], []
    idx = 0
    page = 1
    while idx < N and page <= 6:
        data = json.loads(get(API.format(page=page)))
        results = data.get("results", [])
        if page == 1:
            print(f"  {data.get('result_count')} total matches; trying to bank {N}.")
        if not results:
            break
        page += 1
        for r in results:
            if idx >= N:
                break
            url = r.get("url")
            if not url:
                continue
            try:
                raw = get(url)
                img = Image.open(io.BytesIO(raw))
                if min(img.size) < 300:
                    continue  # too small to look good
                idx += 1
                name = f"dog-{idx:02d}.jpg"
                square(img, OUT_SIZE).save(DOGS / name, "JPEG", quality=82, optimize=True)
                files.append(name)
                sources.append({
                    "file": name,
                    "license": r.get("license"),
                    "creator": r.get("creator"),
                    "title": r.get("title"),
                    "source_page": r.get("foreign_landing_url"),
                    "image_url": url,
                })
                print(f"  ✓ {name}  [{r.get('license')}]  {(r.get('title') or '')[:40]}")
            except Exception as e:  # skip a dead URL / bad image, keep going
                print(f"  … skipped one ({type(e).__name__})")
                continue

    if len(files) < 6:
        raise SystemExit(f"Only banked {len(files)} dogs — network issue? Aborting.")

    MANIFEST.write_text(
        "/* AUTO-GENERATED by tools/fetch_real_dogs.py — bundled real dog photos. */\n"
        "globalThis.ChienternetDogs = " + json.dumps(files) + ";\n"
    )
    lines = [
        "# Bundled dog photos — sources & licenses",
        "",
        "All images below are **CC0** or **Public Domain Mark (PDM)** — no attribution",
        "legally required; recorded here for provenance and good manners.",
        "",
    ]
    for s in sources:
        lines.append(f"- **{s['file']}** — {s['license']} — "
                     f"\"{s['title']}\" by {s['creator'] or 'unknown'} — {s['source_page']}")
    SOURCES.write_text("\n".join(lines) + "\n")

    print(f"\nBanked {len(files)} real dogs -> {DOGS}")
    print(f"Wrote {MANIFEST.name} and {SOURCES.name}")


if __name__ == "__main__":
    main()
