#!/usr/bin/env python3
"""Fetch REAL dog-bark sounds (CC0 only) and trim them into crisp short barks.

Sources via the Openverse audio API filtered to CC0 (no attribution required,
safe to bundle). Prefers short clips (single barks), then uses ffmpeg to strip
silence, cap length, fade the tail and loudness-normalise so every bark punches
at the same level.

Outputs: assets/sounds/bark-1.mp3 ... bark-N.mp3, src/barks-manifest.js, SOURCES.md
Run:  ./.venv/bin/python tools/fetch_barks.py   (needs ffmpeg)
"""
import json
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOUNDS = ROOT / "assets" / "sounds"
MANIFEST = ROOT / "src" / "barks-manifest.js"
SOURCES = SOUNDS / "SOURCES.md"

N = 5
UA = "chienternet/1.0 (personal joke extension; CC0 bark sounds)"
API = ("https://api.openverse.org/v1/audio/"
       "?q=dog%20bark&license=cc0&page_size=20&page={page}")
MIN_MS, MAX_MS = 200, 1600  # prefer single-bark clips

FFMPEG_FILTER = (
    "silenceremove=start_periods=1:start_threshold=-45dB:detection=peak,"
    "areverse,silenceremove=start_periods=1:start_threshold=-45dB,areverse,"
    "atrim=0:1.0,afade=t=out:st=0.82:d=0.18,loudnorm=I=-15:TP=-1.5:LRA=11"
)


def curl(url, timeout=30):
    p = subprocess.run(["curl", "-sS", "-L", "-A", UA, "--max-time", str(timeout), url],
                       capture_output=True)
    if p.returncode != 0:
        raise RuntimeError(f"curl {p.returncode}: {p.stderr.decode()[:120]}")
    return p.stdout


def main():
    SOUNDS.mkdir(parents=True, exist_ok=True)
    for old in SOUNDS.glob("bark-*.mp3"):
        old.unlink()

    print("Querying Openverse for CC0 dog barks …")
    files, sources = [], []
    idx, page = 0, 1
    while idx < N and page <= 6:
        data = json.loads(curl(API.format(page=page)))
        results = data.get("results", [])
        if not results:
            break
        page += 1
        for r in results:
            if idx >= N:
                break
            dur = r.get("duration") or 0
            url = r.get("url")
            if not url or not (MIN_MS <= dur <= MAX_MS):
                continue
            try:
                raw = curl(url)
                with tempfile.NamedTemporaryFile(suffix=".mp3", delete=False) as tf:
                    tf.write(raw)
                    src_path = tf.name
                idx += 1
                name = f"bark-{idx}.mp3"
                out = SOUNDS / name
                ff = subprocess.run(
                    ["ffmpeg", "-y", "-i", src_path, "-af", FFMPEG_FILTER,
                     "-ac", "1", "-ar", "44100", "-b:a", "96k", str(out)],
                    capture_output=True,
                )
                Path(src_path).unlink(missing_ok=True)
                if ff.returncode != 0 or not out.exists() or out.stat().st_size < 800:
                    idx -= 1
                    out.unlink(missing_ok=True)
                    print(f"  … ffmpeg rejected one ({r.get('title','')[:30]})")
                    continue
                files.append(name)
                sources.append({
                    "file": name, "license": r.get("license"),
                    "creator": r.get("creator"), "title": r.get("title"),
                    "source_page": r.get("foreign_landing_url"), "audio_url": url,
                    "orig_ms": dur,
                })
                print(f"  ✓ {name}  [{r.get('license')}]  {dur}ms  {(r.get('title') or '')[:34]}")
            except Exception as e:
                print(f"  … skipped one ({type(e).__name__})")
                continue

    if len(files) < 2:
        raise SystemExit(f"Only banked {len(files)} barks — network/ffmpeg issue? Aborting.")

    MANIFEST.write_text(
        "/* AUTO-GENERATED by tools/fetch_barks.py — bundled CC0 bark clips. */\n"
        "globalThis.ChienternetBarks = " + json.dumps(files) + ";\n"
    )
    lines = ["# Bundled bark sounds — sources & licenses", "",
             "All clips are **CC0** — no attribution legally required; recorded for provenance.", ""]
    for s in sources:
        lines.append(f"- **{s['file']}** — {s['license']} — \"{s['title']}\" "
                     f"by {s['creator'] or 'unknown'} ({s['orig_ms']}ms) — {s['source_page']}")
    SOURCES.write_text("\n".join(lines) + "\n")
    print(f"\nBanked {len(files)} barks -> {SOUNDS}\nWrote {MANIFEST.name} and {SOURCES.name}")


if __name__ == "__main__":
    main()
